### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by auchri** [vincentbrison/android-easy-cache#11]
After changing the language on my phone, I got following exception:

    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:304)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jakewharton.disklrucache.DiskLruCache$Editor.set(int, java.lang.String)' on a null object reference
            at com.vincentbrison.openlibraries.android.dualcache.lib.DualCache.put(DualCache.java:313)
            at ...
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)#
            at java.lang.Thread.run(Thread.java:818)

[DualCache#313](https://github.com/vincentbrison/android-easy-cache/blob/v2.2.0/lib/src/main/java/com/vincentbrison/openlibraries/android/dualcache/lib/DualCache.java#L313)

**Comment by auchri** [comment]
i think it's because of https://github.com/JakeWharton/DiskLruCache/blob/master/src/main/java/com/jakewharton/disklrucache/DiskLruCache.java#L472

**Comment by vincentbrison** [comment]
Thanks for the detailed explanation. I will look into this.

**Comment by auchri** [comment]
Maybe it would be enough to add `synchronized` to [`put(...)`](https://github.com/vincentbrison/android-easy-cache/blob/v2.2.0/lib/src/main/java/com/vincentbrison/openlibraries/android/dualcache/lib/DualCache.java#L279)

**Comment by vincentbrison** [comment]
It may be enough. I am currently in vacation and can't fix this until next
week. Thus feel free to propose this as a merge request ;) (I usually push
directly those fixes as snapshots on maven, and then if it fixes the issue,
I will release a new  version).

**Comment by vincentbrison** [comment]
Hi, 
To have a better understanding of the situation, do you use the same cache from different threads when this issue is occurring ? 

While this issue is evaluated and before it is fixed, you could use a decorator pattern (https://en.wikipedia.org/wiki/Decorator_pattern) to apply the synchronized solution.

**Comment by auchri** [comment]
Yes, I use the cache for all of my AsyncTask's.

I will try the synchronized methods.

**Comment by vincentbrison** [comment]
From what I understand from DiskLruCache from Jake Wharton, edition (put in our case) will thrown this exception only if two concurrent un-synchronized editions are running on the same entry.

So I imagine this case may occurs for you ?

**Comment by auchri** [comment]
Yes, I think so.

I've created a small class which shows the issue: https://gist.github.com/auchri/82b19ce2df69fa8dbb32

If you call it with `new CacheTest(this, true).run(15);`, it work's well.

But with `new CacheTest(this, false).run(15);`, it throws a `NullPointerException`:

    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jakewharton.disklrucache.DiskLruCache$Editor.set(int, java.lang.String)' on a null object reference
         at com.vincentbrison.openlibraries.android.dualcache.lib.DualCache.put(DualCache.java:313)
         at test.CacheTest.putToCache(CacheTest.java:64)
         at test.CacheTest.access$200(CacheTest.java:11)
         at test.CacheTest$1.run(CacheTest.java:54)

**Comment by vincentbrison** [comment]
Nice :). I think it's a good option to let the put method of my cache to be synchronized on the entry being edited, thus we can still have concurrent modifications on different entries, but atomic ones on the same. What do you think ? 

I could upload a snapshot with this modification within the next 24H. Do you want to do this change through a PR ? However I will do it ;).

**Comment by auchri** [comment]
> I think it's a good option to let the put method of my cache to be synchronized on the entry being edited, thus we can still have concurrent modifications on different entries, but atomic ones on the same. What do you think ?

Yep, that's better than synchronizing the whole method.

> I could upload a snapshot with this modification within the next 24H. Do you want to do this change through a PR ? However I will do it ;).

I've no more time until tomorrow afternoon, so you would be definitely faster if you do it yourself :yum:

**Comment by vincentbrison** [comment]
The 2.2.1-SNAPSHOT version with the above changes is available from https://oss.sonatype.org/content/repositories/snapshots/
It includes the changes from https://github.com/vincentbrison/android-easy-cache/commit/dbcc897de0cbe407f31c05905dbd9ef78ea6a5aa.

Let me know if it fixes the issue ;)

**Comment by vincentbrison** [comment]
I may also add your gist in the tests of the lib to ensure proper validation for final release ;)

**Comment by auchri** [comment]
I think it's fixed, but I'm not sure..After I changed the version of the library, it crashed. Then I cleaned the project and now it works without problems :confused:

**Comment by vincentbrison** [comment]
Ok, thanks for the feedback. Then I will test update from 2.2.0 to 2.2.1,
and add concurrent tests to be sure everything is fine.

2015-10-07 20:58 GMT+02:00 auchri <notifications@github.com>:

> I think it's fixed, but I'm not sure..After I changed the version of the
> library, it crashed. Then I cleaned the project and now it works without
> problems [image: :confused:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vincentbrison/android-easy-cache/issues/11#issuecomment-146293798>
> .
>



-- 
Android enthusiast : vincentbrison.com

**Comment by auchri** [comment]
Thanks for the fast fix! :+1:

**Comment by auchri** [comment]
It's not fixed:

    java.lang.NullPointerException
        at com.vincentbrison.openlibraries.android.dualcache.lib.DualCache.put(DualCache.java:319)
        at com.test.CacheTest.putToCache(CacheTest.java:64)
        at com.test.CacheTest.access$200(CacheTest.java:11)
        at com.test.CacheTest$1.run(CacheTest.java:54)

**Comment by vincentbrison** [comment]
Ok I will look into this again this WE to provide something before monday

**Comment by auchri** [comment]
Any progress on this?

**Comment by vincentbrison** [comment]
I will update this tonight or tomorrow :/. I finally did not had the time
to work on it this we sry. Thus to not suffer from my development, I
recommend you to use the decorator pattern with synchronous methods :/

**Comment by vincentbrison** [comment]
I am currently working on this. Writing tests shown me there are a lot of specific cases to take in account. Thus, until I fix them all, the "not so good looking but working fine" solution is to use a decorator to synchronize each method of the dualcache on a common lock object.

**Comment by vincentbrison** [comment]
Hi,
A new version is available at : 
The 2.2.1-SNAPSHOT version with the above changes is available from https://oss.sonatype.org/content/repositories/snapshots/
I have been working on read write lock featuring a more complex lock on each entry.
Right know it working well with 10 threads doing random operations on each cache configuration. If you have the time to test it, it would be great. Have a nice WE.

**Comment by auchri** [comment]
> A new version is available at : 
The 2.2.1-SNAPSHOT version with the above changes is available from https://oss.sonatype.org/content/repositories/snapshots/

Are you sure? I'm not able to get a version with the changes from the latest commits.

**Comment by vincentbrison** [comment]
That's weird. Follwing this url :
https://oss.sonatype.org/content/repositories/snapshots/com/vincentbrison/openlibraries/android/dualcache/
The snapshot has been updated. I think you need to clear the project to be
sure to get the last snapshot.

2015-10-19 11:31 GMT+02:00 auchri <notifications@github.com>:

> A new version is available at :
> The 2.2.1-SNAPSHOT version with the above changes is available from
> https://oss.sonatype.org/content/repositories/snapshots/
>
> Are you sure? I'm not able to get a version with the changes from the
> latest commits.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vincentbrison/android-easy-cache/issues/11#issuecomment-149160032>
> .
>



-- 
Android enthusiast : vincentbrison.com

**Comment by auchri** [comment]
Definitely fixed :)

    new AsyncTask<Void, Void, Void>() {
        @Override
        protected Void doInBackground(Void... voids) {
            for (int i = 0; i < 30; i++) {
                CacheTest.create(MainActivity.this, false).run(80);
                SystemClock.sleep(2500);
            }

            return null;
        }
    }.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR);

-> No exception :+1:

**Comment by auchri** [comment]
Crashed again :/

    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jakewharton.disklrucache.DiskLruCache$Editor.set(int, java.lang.String)' on a null object reference
       at com.vincentbrison.openlibraries.android.dualcache.lib.DualCache.put(DualCache.java:338)

**Comment by vincentbrison** [comment]
:/
It seems that 2 concurrents editions are running on the same entry. I will test more this case tonight.

**Comment by vincentbrison** [comment]
Just to be able to recreate the issue, could you give me the configuration of the cache you are using ?

**Comment by auchri** [comment]
It's the same as the one in my gist: https://gist.github.com/auchri/82b19ce2df69fa8dbb32

**Comment by vincentbrison** [comment]
Hi again,
I am able to recreate this issue. I hope to update the snapshot before tomorrow. I would like to thank you for your patience.

**Comment by vincentbrison** [comment]
A new version is available at : 
The 2.2.1-SNAPSHOT version with the above changes is available from https://oss.sonatype.org/content/repositories/snapshots/

I rewrote my concurrent implementation using java.util.concurrent.locks. Much less code, same performances, and it seems to work. I also added a test which represent your configuration.

**Comment by auchri** [comment]
:(

    java.lang.NullPointerException: Attempt to invoke virtual method 'com.jakewharton.disklrucache.DiskLruCache$Editor com.jakewharton.disklrucache.DiskLruCache.edit(java.lang.String)' on a null object reference
        at com.vincentbrison.openlibraries.android.dualcache.lib.DualCache.put(DualCache.java:328)

**Comment by vincentbrison** [comment]
At least I fixed other issues... You  are sure you clean your project to get the last snapshot :/. You observe this issue with your gist or from your application ?

**Comment by auchri** [comment]
I try it with my gist

    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jakewharton.disklrucache.DiskLruCache$Editor.set(int, java.lang.String)' on a null object reference
        at com.vincentbrison.openlibraries.android.dualcache.lib.DualCache.put(DualCache.java:329)
        at com.test.CacheTest.putToCache(CacheTest.java:71)
        at com.test.CacheTest.access$200(CacheTest.java:14)
        at com.test.CacheTest$1.run(CacheTest.java:61)

called with

    new AsyncTask<Void, Void, Void>() {
        @Override
        protected Void doInBackground(Void... voids) {
            for (int i = 0; i < 50; i++) {
                CacheTest.create(MainActivity.this, false).run(100);
                SystemClock.sleep(2500);
            }

            return null;
        }
    }.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR);

**Comment by vincentbrison** [comment]
Good, so I can recreate exactly your issue :)

**Comment by vincentbrison** [comment]
I think there is an issue in your test 


    new AsyncTask<Void, Void, Void>() {
        @Override
        protected Void doInBackground(Void... voids) {
            for (int i = 0; i < 50; i++) {
                CacheTest.create(MainActivity.this, false).run(100);
                SystemClock.sleep(2500);
            }

            return null;
        }
    }.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR);

This code will create several instances of caches, with the same cache name. Thus these instances will share the same file for the disk layer. But the instances are not synchronized between them. Then, even if the threads working on an instance are synchronized, there are not synchronized among the cache instances, which may produce your issue. Do you agree ?
I run

**Comment by auchri** [comment]
Oh yes, that's possible. I assume you fixed it, thank you!! :+1:
