### ISSUE TITLE
Bitmap Cache

### ISSUE THREAD

**Issue by unNene** [vincentbrison/android-easy-cache#18]
Hi,

I want to cache Bitmap objects.

I have this:
private static final int RAM_MAX_SIZE = 2048;

DualCacheLogUtils.enableLog();
DualCacheContextUtils.setContext(getApplicationContext());
cache = new DualCacheBuilder<Bitmap>("bitmapCache", 1, Bitmap.class)
                .useDefaultSerializerInRam(RAM_MAX_SIZE)
                .noDisk();

And I have DataHolder where I have reference to "cache" instance.

DataHolder.getInstance().setCache(cache);

When I put object to cache:
key = "data1";
cache.put(key, result);

and immediately  I try to get this object with:
 Bitmap bm = cache.get(key);

bm is equal to null.

Class that implements SizeOf<Bitmap> is returning  -> object.getHeight() * object.getWidth() * 4

What I'm doing wrong ?

**Comment by vincentbrison** [comment]
Hi,

I think you would use the following config : 
new DualCacheBuilder("bitmapCache", 1, Bitmap.class)
                .useReferenceInRam(RAM_MAX_SIZE, YourImplementationOfSizeOf)
                .noDisk(); 
Since useDefaultSerializerInRam means the cache will serialize your Bitmap object in String using json mapping. Could you try like that :) ?

**Comment by unNene** [comment]
Hi,

Thank for your response, I tried but is not working.

**Comment by vincentbrison** [comment]
Hello again,

You may use a cache too small. If you set 2048 as cache size, and your sizeOf is : 
object.getHeight() * object.getWidth() * 4
A bitmap with the size 50*50 pixels will have a size of 10000, which is already bigger than your cache size. Could you try with a bigger cache size ?

**Comment by unNene** [comment]
Hello,

You are right, problem was in cache size. Now is working, thank you.
