### ISSUE TITLE
Crashes on Prograud with minifyEnabled true

### ISSUE THREAD

**Issue by manishmodi** [vincentbrison/android-easy-cache#19]
It's working perfectly fine in debug mode. But once I try with signed apk having progaurd with minifyEnabled true, it crashes. 
I have tried using
 -keep class com.vincentbrison.** { *; }
 -dontwarn com.vincentbrison.**
But no luck yet.

**Comment by vincentbrison** [comment]
Hi,

Since the library has the following dependencies :
> compile 'com.jakewharton:disklrucache:2.0.2'
> compile 'com.fasterxml.jackson.core:jackson-databind:2.4.2'

You may also want to keep `com.jakewharton`and jackson with something like https://github.com/auth0/Lock.Android/blob/master/proguard/proguard-jackson-2.pro

**Comment by vincentbrison** [comment]
Hi,

Any update on this ? Did you manage to fix your Proguard configuration ?

**Comment by manishmodi** [comment]
Yes, thanks.

**Comment by jaydeepmalviay** [comment]
Hi,
I m facing same problem and unable to access "https://github.com/auth0/Lock.Android/blob/master/proguard/proguard-jackson-2.pro" for solution.
please let me know the fix.

**Comment by vincentbrison** [comment]
Hi,
This URL is unrelated with this project.
