### ISSUE TITLE
Add feature to remove from cache

### ISSUE THREAD

**Issue by imperat0r** [vincentbrison/android-easy-cache#22]
Is it really possible there is no way to remove from cache. Something like cache.remove(key)?
Example, I call web service to get some object. I want to cache that object (the way of implementing of cache is not important to me). What is important is that when I use web service to update that object I want to invalidate cache. I think it is very common requirement, but cannot find any good library which does this.

**Comment by vincentbrison** [comment]
Hi
You certainly looking for method :

```
public void delete(String key)
```

of the class `DualCache`.
Best regard
