### ISSUE TITLE
Provide examples for caching Bitmaps, Files etc

### ISSUE THREAD

**Issue by cperry-gpsw** [vincentbrison/android-easy-cache#23]
I want to use your library for disk caching some JPG images. I don't see how to do this, I looked at your methods

```java
useCustomSerializerInDisk()
```
and

```java
useDefaultSerializerInDisk()
```

both seem to assume I want to store data as Strings, which isn't a very good assumption.

**Comment by vincentbrison** [comment]
Hi,

You could [use this configuration](https://github.com/vincentbrison/android-easy-cache/blob/master/lib/src/androidTest/java/com/vincentbrison/openlibraries/android/dualcache/lib/configurationsToTest/RamReferenceDiskCustomSerializer.java), as its done in one of the test of the lib.

This way bitmaps will be cached in RAM through their references, and you need to provide a serializer on disk in you want to persist the cache.

So you still need to compute the size of the bitmap in RAM, to allow the cache to apply LRU policy on the RAM layer. You can use any policy you want. For example you can say that one bitmap has the value of 1 and your RAM cache has the size of 10, which allow you to store 10 bitmap before the LRU policy start evicting bitmaps.

To store bitmap on disk you will need to provide a way to serialize / deserialize your bitmap through the interface https://github.com/vincentbrison/android-easy-cache/blob/master/lib/src/main/java/com/vincentbrison/openlibraries/android/dualcache/lib/Serializer.java. You can for example convert your bitmap to Base64 http://stackoverflow.com/questions/13562429/how-many-ways-to-convert-bitmap-to-string-and-vice-versa.

Keep in mind that when you put a bitmap in the cache, it will be put in the RAM and the disk layer. When you get the bitmap, the cache will try to load the bitmap from RAM, and if it is not present in RAM, it will try to load it from disk (and put again the bitmap in RAM btw).

BR

**Comment by vincentbrison** [comment]
BTW the cache fully support multi threading. So you can do multiple `get` from different threads, like `Asynctask`, without any problem (save and load bitmap from cache may be time consuming).

**Comment by vincentbrison** [comment]
Hi,
I close this issue, since you did not provide feedback on this. You can still i(f you feel the need) reopen this do get more information.
