### ISSUE TITLE
Apache is deprecated

### ISSUE THREAD

**Issue by softvision-mariusduna** [vincentbrison/android-easy-cache#24]
import org.apache.commons.io.IOUtils; 
Please remove any dependencies to apache.

**Comment by vincentbrison** [comment]
Hi,

Could you provide more information about this issue, like where do you find this :
`import org.apache.commons.io.IOUtils;`

Could you also point me where Apache says `org.apache.commons.io`is deprecated ?

BR.

**Comment by softvision-mariusduna** [comment]
You can close the issue, there was another lib that use yours: https://github.com/fhucho/simple-disk-cache , there they have this bug.

When upload the apk to the play store then it shows 0 supported devices, this because of: compile 'org.apache.directory.studio:org.apache.commons.io:2.4'

Others had the same issue: http://stackoverflow.com/questions/14020237/android-app-is-supported-by-0-devices

I removed the upper library and the app becomes compatible with lot of devices.

Anyway you tit a good job here
